config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'welcome/index'

  root 'welcome#index'
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :products do
    resources :reviews, :only => [:show, :create, :destroy]
  end 
  resources :users, :only => [:new, :create]

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, :presence => true
	validates :price_in_cents, :numericality => {:only_integer => true}
	has_many :reviews
	has_many :users, :through => :reviews

def formatted_price
	price_in_dollars = price_in_cents.to_f / 100
	sprintf("%.2f", price_in_dollars)
end

end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :comment, :presence => true

	belongs_to :user
	belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews
	has_many :products, :through => :reviews

	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :text)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:show]
  
  def index
    if params[:search]
      @products = Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
  	else
      @products = Product.all
    end

    @products = @products.page(params[:page]).order('products.created_at DESC')

   respond_to do |format|
      format.html
      format.js
    end

  end

  def show
  	@product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
    
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)

  	if @product.save
  		redirect_to products_url
  	else
  		render :new
  	end

  end

  def update
  	@product = Product.find(params[:id])

  	if @product.update_attributes(product_params)
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
  end

  private
  def product_params
  	params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user_id = current_user.id

    respond_to do |format|
  	if @review.save
      format.html {redirect_to product_path(@product.id), notice: 'Review added.'}
      format.js {}
  	else
      format.html { render 'products/show', alert: 'There was an error.'}
      format.js {}
  	end
  end

  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private
  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "logged in"
  	else
      flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, :notice => "Signed up"
  	else
      flash.now[:alert] = "Sign up not successful"
  		render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rainforest</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash [:alert] %>
	<p id="alert"><%= flash[:alert] %></p>
	<% end %>

	<%= yield %>

	<p class="userinfo">
		<% if current_user %>
			Signed in as <%= current_user.email %>. <% link_to "Log out", session_path("current"), :method => :delete %>
		<% else %>
			<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
		<% end %>
	</p>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

<% if @product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
	<ul>
		<% @product.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class = "field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</div>
<div class="field">
	<%= f.label :price_in_cents %><br />
	<%= f.number_field :price_in_cents %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product.id) do %>
 <h3>
   <%= number_to_currency(product.formatted_price) %>
   <%= product.name %>
 </h3>
<% end %>
<!-- keeps the description to 100 characters or less -->
<p><%= truncate(product.description, length: 200) %></p>

app/views/products/_review_form_errors.html.erb
	<% if @review.errors.any? %>
	<div id = "error_explanation">
		<h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved: </h2>
		<ul>
			<% @review.errors.full_messages.each do |msg| %>
			<div class="alert">
			<li><%= msg %></li>
			</div>
			<% end %>
		</ul>
	</div>
	<% end %>

app/views/products/_reviews.html.erb
	<% @product.reviews.each do |review| %>
	<div class="review">
		<div class="poster">
		<% if review.user != nil %>
			<em> by <%= review.user.email %></em>
			Added on: <%= review.created_at %>
		<% end %>
		</div>
	<p class="comment">
		<%= review.comment %><br>
	</p>
	</div>
	<% end %>

app/views/products/edit.html.erb
<h1>Edit a product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search" %>
<% end %>

<%= link_to 'New Product', new_product_path %>

<!-- renders a helpful message with numbers of displayed vs. total entries -->

<h1>Products <small><%= page_entries_info @products %></small></h1>

<hr/>

<div id="products">
	<%= render @products %>
</div>

<%= paginate @products %>

app/views/products/index.js.erb
$('#products').append('<%= j render(@products) %>');
$('.pagination').replaceWith("<%= j(paginate @products) %>")

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
	<strong>Name: </strong>
	<%= @product.name %>
</p>

<p>
	<strong>Description: </strong>
	<%= @product.description %>
</p>

<p>
<strong>Price: </strong>
<%= @product.formatted_price %>

<% if current_user %>
	<h3>Reviews</h3>

	<p>Reviews for <%= @product.name %></p>

<div id="review-list">
	<%= render :partial => "reviews" %>
</div>

	<h4>New Review</h4>

	<%= form_for ([@product, @review]), :remote => true do |f| %>
	<div id="review-form-errors">
	<%= render :partial => "/products/review_form_errors" %>
	</div>

	<div class="field">
		<%= f.label :comment %><br />
		<%= f.text_area :comment %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
		<% end %>

	<% else %>
		<p>Please <%= link_to "log in", new_session_path %> to add a review.</p>

	<% end %>
	
	<%= link_to 'Back', products_path %>

<script type="text/javascript">
$(function() {
	$("#new_review")
		.on('ajax:beforeSend', function() { 
			$("input[type='submit']")
			.val('Saving...')
			.attr('disabled', 'disabled');
		})
		.on('ajax:complete', function() {
			$("input[type='submit']")
			.val('Create Review')
			.removeAttr('disabled');
		});
});
</script>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class = "error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %></br />
		<%= f.text_field :email %><br />
	</div>
	<div class ="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %><br />
	</div>
	<div class="actions"><%= f.submit %></div>
	<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the rainforest</h1>

<%= link_to 'Products page', controller: 'products' %>